### PR TITLE
dubnium updates

### PR DESCRIPTION
**Pull request by jpw**

### CODE REVIEW

**Comment by benjclark** [comment]
Oh, actually, just thought of something. Doesn't the node version need to be updated in the engines -> node field in package.json ?

**Comment by jpw** [comment]
hmm yeah thanks, I always ignore that, as does most software... will see if i can remove it

**Comment by alexkilgour** [comment]
As far as I am aware the `engines` field is advisory, so can be removed

**Comment by jpw** [comment]
also had to rm some travis config to run the tests on all branches... seems to be a historic restriction to do with semver releases candidate branches (or similar). We want to run the tests on all branches so have removed that bit of the travis config.

**Pull request merged**
